### PR TITLE
Remove issues

### PR DESCRIPTION
**Pull request by aaronliu0130**
Issues are nonexistent for some reason

### CODE REVIEW

**Comment by Felipefpl** [comment]
lots of fights in the past regarding the content of the site, that's why they dont exist now. ;)

**Comment by aaronliu0130** [comment]
> lots of fights in the past regarding the content of the site, that's why they dont exist now. ;)

Is that relevant to this pull? I've actually seen the issues before. But anyways, this thing is misleading.

**Comment by Felipefpl** [comment]
>  Is that relevant to this pull?

Yes, the fights made the issues' section disappear. I guess the owner dont want to argue anymore about those.

**Comment by aaronliu0130** [comment]
> > Is that relevant to this pull?
> 
> Yes, the fights made the issues' section disappear. I guess the owner dont want to argue anymore about those.

Still waiting for @MachineGunnur to respond.

**Comment by MachineGunnur** [comment]
feli is correct.

**Pull request closed without merging**
